### ISSUE TITLE
Container is too slow

### ISSUE THREAD

**Issue by plaviano** [echo-magento/docker-magento2#3]
Hello there!

I just installed the docker image and I noticed it is extremely slow while loading pages.

Is there any kind of tuning I can make, or somewhere I can look for tuning the speed of page load? Each page load takes minutes to complete, that's why I'm asking.

Thanks in advance!

**Comment by echo-magento** [comment]
Hi!
What server specifications and OS do you use? Unfortunately, we don't support macOS and Win, Linux only.
Also, the problem may be in third-party modules, try checking the speed on clean M2 version

**Comment by plaviano** [comment]
Yes, I was doing on Windows.

It worked fine, just too slow 😅 (and I couldn't deploy the sample data too)

My specs:

Microsoft Windows 10 Home Single Language
Version: 10.0.19043 Build 19043

Docker Desktop 3.4.0 (65384)
Engine: 20.10.7
Compose: 1.29.2
Credential Helper: 0.6.4
Kubernetes: v1.21.1
Snyk: v1.563.0

Thanks for the notes anyway 😃

**Comment by echo-magento** [comment]
We recommend using a Linux  operating system for best performance. You will get an increase in speed several times.
