### ISSUE TITLE
Getting this error on mac

### ISSUE THREAD

**Issue by 200263830** [echo-magento/docker-magento2#4]
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:578266a8f2de6e1a6896c487dd45cfc901a82ddf50be13bb7c56f97ecd693f77: not found

I am trying to use this on my mac and i am getting this error.

**Comment by adrifkat** [comment]
Hi @200263830,
Unfortunately, we don't support macOS and Win, Linux only.
